[package]
name = "ngn"
version = "0.1.0"
edition = "2021"
description = "P2P"

[dependencies]
tokio = { version = "1", features = ["full"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }
futures-util = "0.3"

[[example]]
name = "dbus"
crate-type = ["bin"]
