/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NgnSessionProxy */

#ifndef _Included_NgnSessionProxy
#define _Included_NgnSessionProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NgnSessionProxy
 * Method:    ngn_session_init
 * Signature: (LNgnSessionProxy;)J
 */
JNIEXPORT jlong JNICALL Java_NgnSessionProxy_ngn_1session_1init
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
